version: 2
jobs:
   build:
      docker:
        - image: circleci/ruby:2.6.6-node
          environment:
            RAILS_ENV: test
            PGHOST: 127.0.0.1
            PGUSER: root
        - image: circleci/postgres
          environment:
            POSTGRES_USER: root
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_DB: HotSpringMap_test

      working_directory: ~/HotSpringMap
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "Gemfile.lock" }}
              - v1-dependencies-
        - run:
            name: install dependencies
            command: |
              gem install bundler -v 2.1.4
              bundle install --jobs=4 --retry=3 --path vendor/bundle
        - save_cache:
            key: v1-dependencies-{{ checksum "Gemfile.lock" }}
            paths:
              - ./vendor/bundle
        
        # Database setup
        - run: rm ./config/database.yml
        - run: mv ./config/database.yml.ci ./config/database.yml
        - run:
            name: Prepare db
            command: |
              bundle exec rake db:create db:schema:load --trace

        - run:
            name: rspec
            command: bundle exec rspec
        - run:
            name: rubocop
            command: bundle exec rubocop