version: 2
jobs:
   build:
      docker:
        - image: circleci/ruby:2.6.6-node
          environment:
            #自身の登録しているユーザに変える。
            POSTGRES_USER: postgres 
            PGHOST: db
            RAILS_ENV: test
        - image: circleci/postgres
          environment:
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_DB: HotSpringMap_test

      working_directory: ~/HotSpringMap
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "Gemfile.lock" }}
              - v1-dependencies-
        - run:
            name: install dependencies
            command: |
              gem install bundler -v 2.1.4
              bundle install --jobs=4 --retry=3 --path vendor/bundle
        - save_cache:
            key: v1-dependencies-{{ checksum "Gemfile.lock" }}
            paths:
              - ./vendor/bundle

        - run:
            name: DBの起動を待つ
            command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s

        - run: bundle exec rake db:create
        - run: bundle exec rake db:schema:load

        - run:
            name: rspec
            command: bundle exec rspec
        - run:
            name: rubocop
            command: bundle exec rubocop